### ISSUE TITLE
inline bug related to structures

### ISSUE THREAD

**Issue by Xylemon** [fte-team/fteqw#132]
https://sourceforge.net/p/fteqw/tickets/86/

paril101 wrote on 2020-07-08:

inline functions that are passed structure values always seem to pass `value+0` instead of the correct offset. MVP:
```
struct mystruct
{
    int x;
    int y;
} stroct;

inline int(int s) test_inline =
{
    return s;
};

void() test_func =
{
    int xyz = test_inline(stroct.y);
};
```
Check generated ASM for test_func; note that it passes `stroct+0` which is x, not y.

**Comment by fhomolka** [comment]
This was fixed at some point as the generated ASM given the same example code now shows `stroct+1`, which should be y.

**Comment by Xylemon** [comment]
Thanks for testing!
