### ISSUE TITLE
Shadowing static generates warning

### ISSUE THREAD

**Issue by Xylemon** [fte-team/fteqw#134]
https://sourceforge.net/p/fteqw/tickets/92/

paril101 wrote on 2020-07-09:

attempting to shadow a static variable (in a different file, no less) generates a warning about the name being static, even though it's not the same file.

**Comment by fhomolka** [comment]
This was seemingly fixed, as the compiler will no longer give a shadowing warning for static names that are in different files.
Example used
`first.qc`:
```cpp
static float val = 3;
float() get_val =
{
	return val;
};
```

`second.qc`:
```cpp
static float val = 4;

float() get_second_val =
{
	return val;
};
```

and a `progs.src` that defines an empty main and includes both files.

**Comment by Xylemon** [comment]
Thanks for testing!
