### ISSUE TITLE
Stuttering issue caused by music

### ISSUE THREAD

**Issue by Xylemon** [fte-team/fteqw#136]
https://sourceforge.net/p/fteqw/tickets/94/

vini1264 wrote on 2020-09-10:

Hello, I've downloaded the latest version of FTEQW and it plays nice but at some moment it starts to stutter and drop frames like crazy. I think it's somehow related with the music files, because when I removed the music files in the id1 folder the stuttering simply stopped, also when I reduced the audio quality the stuttering reduced but not entirely with the music folder in it. I'm reporting this problem because it's annoying to not have ingame music just because of stutters.

**Comment by Xylemon** [comment]
bigfrags wrote on 2020-09-10:

I'm getting the same problem. If I restart the sound, it temporarily resolves the issue but after some time the problem comes back.

A video demonstrating the problem:

https://www.youtube.com/watch?v=x_4QmLHtI9Y

**Comment by Xylemon** [comment]
bigfrags wrote on 2022-03-14:

Nevermind

**Comment by Xylemon** [comment]
Never have experienced this, it probably is an issue on your end. If others can reproduce, please comment here or open a new issue.

**Comment by demsix** [comment]
@Xylemon 

I've recreated this on 2 completely separate devices (Intel Laptop / AMD Desktop)

1) Download [FTEQW](https://www.fteqw.org/dl/fteqw_win64.zip) and move into an empty directory
2) Copy id1 folder (Containing PAK0.pak, ./music, no configs) 
3) Start FTEQW and enter "show_fps 2" into console
4) Wait several minutes on and you'll see the frametime spike

If I enter "snd_restart" into the console the frametime settles.

[Here's a video of the same problem on my laptop](https://www.youtube.com/watch?v=aTgbI4ckxzU)

**Comment by Xylemon** [comment]
OK thank you @demsix, we'll look into this then! What format is the music? OGG, MP3, FLAC?

**Comment by demsix** [comment]
> OK thank you @demsix, we'll look into this then! What format is the music? OGG, MP3, FLAC?

[This pack](https://www.quaddicted.com/files/music/quake_campaign_soundtrack.zip) is what I'm using and it contains both the .ogg and .mp3 files. 

If I copy just the .mp3 files into ./id1/music, I don't get any music.
If I copy just the .ogg files into ./id1/music, the music plays (But eventually the game stutters)

> Also does it stutter when a track changes or just seemingly random?

When the map loads its fine, but the stutters get worse over time. A few minutes in a map and it becomes very noticable.

**Comment by Theuaredead** [comment]
Throwing my hat into the ring here.

This bug affects all games that use OGG playback on Windows-based machines. No matter if its 32-bit or 64-bit.

However: The stuttering only occurs on the _first_ loop of the music (when the track first starts) and any loop afterwards lacks the stutter. If the track changes it will cause the stutter to return till the track finishes and plays again.

**Comment by demsix** [comment]
Interesting find on the first playthrough being affected by not subsequent. Strange. 

Is there a way to get mp3 music in FTE? Wonder if it behaves the same.

**Comment by Theuaredead** [comment]
> Interesting find on the first playthrough being affected by not subsequent. Strange.
> 
> Is there a way to get mp3 music in FTE? Wonder if it behaves the same.

I'm unsure on MP3 support with FTE, I don't think it has support for it. But don't take my word on the matter.

 I have tested WAVs and the stutter is not present on playback. So the issue seems isolated to OGGs.

**Comment by Xylemon** [comment]
Seems we have identified the offending commit, and are looking into a fix as we speak.

The commit in question: https://github.com/fte-team/fteqw/commit/5159a801ff07463062b68660628c0b7992b8e49a#diff-14ce3629553d7612cce9295ca216b6b467076ccc9c698c847099cd8355e93bec
