### ISSUE TITLE
Bump texture variants not working

### ISSUE THREAD

**Issue by Xylemon** [fte-team/fteqw#137]
https://sourceforge.net/p/fteqw/tickets/98/

hemebond wrote on 2021-01-30:

I have custom TGA texture overrides in `~/.local/share/quake/id1_tex/textures/` and the `_bump` variants are not working in-game. Normal (`_norm`) and other variants work fine.

**Comment by Xylemon** [comment]
@eukara wrote on 2022-03-07:

This was solved in IRC if I remember correctly.
Anyway, normal maps do work, so closing this old issue!

**Comment by Xylemon** [comment]
hemebond wrote on 2022-03-07:

I just downloaded 6202 and it doesn't appear to work. Perhaps my test isn't working and someone else can confirm either way.
 
Last edit: Hemebond 2022-03-07

**Comment by Xylemon** [comment]
@eukara wrote on 2022-03-07:

it seems the after-quake etc. packs don't use _bump, but ship with _norm.
I found some old disabled code routine that did the bump replacement image loading and will prod around if this is designed behaviour!

**Comment by Xylemon** [comment]
@eukara wrote on 2022-03-07:

There are places all over (gl_shader, image.c inside client) that all attempt to support bump. Letting Spike know that this is completely broken and we'll have a fix asap.

**Comment by hemebond** [comment]
This was supposedly fixed in the version from fteqw.org but I just tested and I can not see it loading my bump textures.

**Comment by Xylemon** [comment]
I decided to reinvestigate this again, as I was pretty certain the engine was checking for `_bump`. I downloaded your PK3s (both [RTLights](https://github.com/hemebond/quake-rtlights ) and [Textures](https://github.com/hemebond/quake-textures)), and then executed `fps_preset nice` in the engine (the CVARs it sets can be seen [here](https://github.com/fte-team/fteqw/blob/master/engine/client/m_options.c#L1066)).

When I loaded up the textures, they looked very broken with FTE warning that the textures were not greyscale. After taking a peak at one of the _bump textures in GIMP, they are black and white but still retain RGB information. If I set it to greyscale (Image > Mode > Greyscale) and export the _bump texture works properly.

You probably want to fix the bumpmap textures that contain RGB information, as it takes up unnecessary disk space. FTE is trying to do the _right_ thing here and as a result not loading them (properly) when RGB is present.

This was also tested with the Linux binary from fteqw.org

Texture on left contains RGB information, texture on right is true Greyscale `_bump`:
![fte-20230927135917-0](https://github.com/fte-team/fteqw/assets/7539500/2164a589-dbd8-4d54-b90b-a8550573ba31)

The warnings from FTE's console:
![fte-20230927140006-0](https://github.com/fte-team/fteqw/assets/7539500/ec86221c-69c4-45ef-ae86-7acfd12b1265)

Version output showing the same as fteqw.org:
![fte-20230927140027-0](https://github.com/fte-team/fteqw/assets/7539500/e26c489c-e991-4aa9-ac61-25081e6b1b28)

**Comment by hemebond** [comment]
@Xylemon Thank you for the info. I get no warnings in the console so I had no idea. Also, my current bump map images are JPEG, so will I need to change that too?

**Comment by Xylemon** [comment]
No problem. As for JPEG, I haven't tested it but I'm sure JPEG will work. The engine binaries on the site have JPEG support statically built into the binary.

If anything else is broken let us know, otherwise I think we can close the issue. I'll be sure to check on your packs in the future, they seem pretty neat and are good for testing.

**Comment by hemebond** [comment]
I just tested and JPEG bump maps are not loaded, but creating a TGA from the JPEG works; I created the TGA from `+0basebtn_bump.jpg` and can see if "bumping".

**Comment by Xylemon** [comment]
Sorry for the late response.

> I just tested and JPEG bump maps are not loaded, but creating a TGA from the JPEG works; I created the `+0basebtn_bump.tga` from `+0basebtn_bump.jpg` and can see it popping with the animation.

OK I'll be sure to let Spike know. For now I think I'm going to close this issue since `_bump` textures work, thanks for testing.
