### ISSUE TITLE
pk3dir gets loaded before PK3/PK4

### ISSUE THREAD

**Issue by Xylemon** [fte-team/fteqw#143]
https://sourceforge.net/p/fteqw/tickets/127/

@Xylemon wrote on 2022-03-02:

If you're storing content in pk3dirs, it won't override data from PK3/PK4s. From what I recall, this changed/broke in the last couple months.

**Comment by fhomolka** [comment]
This appears to have been fixed. 
The map in screenshot below looks the same, just without my modification to the texture.

![fte-20230712104943-0](https://github.com/fte-team/fteqw/assets/21170980/bc637672-a5ea-494c-aabf-b094078862ea)

**Comment by Xylemon** [comment]
Awesome! Wanted to confirm this myself with what caused me to report this awhile ago:

![fte-20230712190418-0](https://github.com/fte-team/fteqw/assets/7539500/23fd2198-90bd-47f0-8cf9-b5e3988042f8)

Thanks for checking this @fhomolka !
