### ISSUE TITLE
why sv_autoSave is disabled for multi-player games?

### ISSUE THREAD

**Issue by Xylemon** [fte-team/fteqw#151]
https://sourceforge.net/p/fteqw/tickets/149/

ferneu1 wrote on 2022-05-30:

I tried to use `sv_autosave` while playing coop and, when it didn't work, I went to the source code and saw that it [explicitly disables auto-saving when there is more than one player](https://sourceforge.net/p/fteqw/code/HEAD/tree/trunk/engine/server/savegame.c#l1518). There are a couple of comments in the code, but they don't really make it clear why it shouldn't be done.

That code is followed by a couple more checks that also disables auto-saving in case the player is using a cheat and also if he is not standing still.

Can use cheats cause problems, or was that done just to avoid helping someone cheating, as the comments in the code seem to imply?

And what is up with not saving unless the player is not moving?

The reason I'm asking all this is that the regular `sv_save` does not perform any of those checks and seems to work just fine when playing coop.

**Comment by Xylemon** [comment]
@Shpoike wrote on 2022-07-01:

why singleplayer:
in singleplayer, you're forced to restart the hour-long map or whatever on death, if you didn't manually save.
in coop, monsters stay dead, there's no 'restart' commands doing the autoreloading, etc. it'd be more effective to autosave on player timeout, though by the time they actually time out they've already lost a load of time anyway.
in deathmatch, you get extra disk access and stalls for no good reason when your average user won't be able to load the saved games anyway.
mostly though, servers are meant to be configure+forget instead of needing persistent admin presence (listen servers have similar behaviours, for consistency in settings if nothing else).

so yeah, most users won't expect (auto)save in multiplayer anyway, and makes the other checks a bit easier, instead of adding annoying extra cvars to configure it separately etc.

other stuff:
cheats prevent saving because developers are generally restarting lots with lots of incompatibilities anyway - or they're loading the same old autosave and don't want it overwritten.

no autosaves when moving prevents people depending on saved games where the player is about to fall into lava, while avoiding any disk-stalls while the player is busy platforming.

so yeah, the checks are just to avoid annoyances instead of technical limitations. if you want to make your own autosave stuff in your gamecode then go for it.

**Comment by Xylemon** [comment]
ferneu1 wrote on 2022-07-01:

Thanks for the clarifications.

Although we do plan on relying mostly on manually saving when playing, I thought we could use auto-saves as a back-up, in case one we forget to save. Since I also modified the code to put timestamps in the auto-save names, there is no risk of overwriting and, if a save was bad because a player was in one of those annoying situations you described, we can just go back to the previous one.

I also understand your point about the performance implications, but I disagree. Auto-saving is not enabled by default and, if someone enables it, it probably means that person is planning on using it, has access to the server and understands the possible performance hits.

What about adding a "forced_auto_save"? One that would disregard all those checks? It would also be great if it worked on a global timer, instead of using the map timer. The use case for that would be when playing a coop campaign. Let's say you set the auto-save time to 15 minutes, but then you finish every map in less than 14 minutes. And forgot to manually save. Then there is crash or you got stuck in a wall (which seems to happen a lot when playing with "sv_nomsec 0") The current auto-save, assuming it allowed one to save in multi-player games, would have never kicked-in and you'd be left with nothing other than your manual saves. Which you forgot to make...

I'd be more than happy to provide a patch for that.

PS: I found it so cool that you can even save and reload while recording a demo and the demo won't stop. Props to whoever done that. Awesome feature.

**Comment by eukara** [comment]
If somebody wants to write and test a PR for this, we're willing to review it.
