### ISSUE TITLE
ex_walkpathtogoal not implemented

### ISSUE THREAD

**Issue by Xylemon** [fte-team/fteqw#153]
https://sourceforge.net/p/fteqw/tickets/151/

neclepsio wrote on 2022-07-29:

While I was playing map horde4 Quake Remaster, Update 3, the map suddenly closed with a message similar to: "builtin 0:ex_walkpathtogoal not implemented".

This happened twice, when spawn entered.

Before the errors, in the console there are:
```
qsrc\mg1\qc/ai.qc : ai_pathtogoal+43
dist:2
qsrc\mg1\qc/ai.qc : ai_run+73
qsrc\mg1\qc/monsters/tarbaby.qc : tbaby_run11+2
```

The release notes of update 3 mention:

Added "walkpathtogoal" QuakeC built-in. This can be used as a drop-in replacement for the existing AI movement to allow any entity to take advantage of bot pathfinding without needing them to be a bot client. Create a friendly dog that does your bidding, or haunted items that run away from the player to avoid being picked up. The world is your oyster!

Remaster Update 3 QuakeC source is at: https://github.com/id-Software/quake-rerelease-qc

**Comment by Xylemon** [comment]
neclepsio wrote on 2022-06-10:

It seems related to https://github.com/id-Software/quake-rerelease-qc/blob/4a992dc9a38436d0b73eae380fd65325f7db833d/quakec_mg1/ai.qc#L891:
```
if ( isHordeMode ) {
    ai_pathtogoal( dist );
} else {
    // head straight in
    movetogoal( dist );     // done in C code...
}
```
ai_pathtogoal (https://github.com/id-Software/quake-rerelease-qc/blob/4a992dc9a38436d0b73eae380fd65325f7db833d/quakec_mg1/ai.qc#L784) then calls walkpathtogoal.

**Comment by Xylemon** [comment]
neclepsio wrote on 2022-06-10:

This is the commit to add the support in QuakeSpasm: https://github.com/Novum/vkQuake/commit/b8e9f8f639ed81be1e88f689e022e83113bee868

It should simply return 0.

**Comment by Xylemon** [comment]
neclepsio wrote on 2022-06-10:

The following patch seems to work.
```
*** pr_cmds.c   2022-07-03 14:45:17.000000000 +0200
--- pr_cmds_new.c   2022-07-31 19:30:30.590612000 +0200
*************** static void QCBUILTIN PF_bprint_qex(pubp
*** 10932,10937 ****
--- 10932,10941 ----
    TL_Reformat(formatted, sizeof(formatted), args, arg);
    SV_BroadcastPrintf (level, "%s", formatted);
  }
+ static void QCBUILTIN PF_sv_walkpathtogoal_qex(pubprogfuncs_t *prinst, struct globalvars_s *pr_globals)
+ {
+     G_FLOAT(OFS_RETURN) = 0; /* PATH_ERROR */
+ }

  #define STUB ,NULL,true
  #if defined(DEBUG) || defined(_DEBUG)
*************** static BuiltinList_t BuiltinList[] = {
*** 11198,11204 ****
    {"ex_bot_movetopoint",PF_Fixme,         0,      0,      0,0,    D("float(entity bot, vector point)", "Behaviour is undocumented.")},
    {"ex_bot_followentity",PF_Fixme,        0,      0,      0,0,    D("float(entity bot, entity goal)", "Behaviour is undocumented.")},
    {"ex_CheckPlayerEXFlags",PF_CheckPlayerEXFlags_qex,0,0, 0,0,    D("float(entity playerEnt)", "Behaviour is undocumented.")},
!   {"ex_walkpathtogoal",PF_Fixme,          0,      0,      0,0,    D("float(float movedist, vector goal)", "Behaviour is undocumented.")},
  //End QuakeEx, for now. :(

  // Tomaz - QuakeC String Manipulation Begin
--- 11202,11208 ----
    {"ex_bot_movetopoint",PF_Fixme,         0,      0,      0,0,    D("float(entity bot, vector point)", "Behaviour is undocumented.")},
    {"ex_bot_followentity",PF_Fixme,        0,      0,      0,0,    D("float(entity bot, entity goal)", "Behaviour is undocumented.")},
    {"ex_CheckPlayerEXFlags",PF_CheckPlayerEXFlags_qex,0,0, 0,0,    D("float(entity playerEnt)", "Behaviour is undocumented.")},
!   {"ex_walkpathtogoal",PF_sv_walkpathtogoal_qex,0,0,      0,0,    D("float(float movedist, vector goal)", "Behaviour is undocumented.")},
  //End QuakeEx, for now. :(

  // Tomaz - QuakeC String Manipulation Begin
```

**Comment by Xylemon** [comment]
@Xylemon wrote on 2022-08-23:

Can you retest with the latest commit?

**Comment by eukara** [comment]
Tested it, seems to run fine!
