### ISSUE TITLE
Deprecated Visual Studio projects in Engine?

### ISSUE THREAD

**Issue by Theuaredead** [fte-team/fteqw#156]
There's a few directories in the "Engine" folder for Visual Studio projects, some of which haven't been updated since 2006.

Are these deprecated? Are Windows users supposed to generate a new project through CMake opposed to the old VS projects?

**Comment by Shpoike** [comment]
Yeah, none of the team use msvc any more, so cmake is the 'official' way to compile FTE in MSVC or other IDEs (while the (gnu)make project is used for public+statically-linked+reproducible+crosscompiled builds).
You'll still have to figure out third-party dependencies yourself. they're MEANT to autodisable-with-warning when missing, so you're likely to be missing stuff like zip or png or ogg or freetype etc support, most you won't care about, some you might.

Frankly a whole load of old stuff needs to be obliterated. :|
