### ISSUE TITLE
r_showbboxes and R_BeginPolygon don't work well together

### ISSUE THREAD

**Issue by shpuld** [fte-team/fteqw#157]
version: Engine Version: FTE build Jan 15 2023 (fteqw.org build)
platform: win10 64bit
gpu: nvidia rtx2070super

if in CSQC_UpdateView you draw 3d polygons before calling addentities, things will look normal until you set r_showbboxes 1/2, at which point things will look garbled like in the attached pic. a workaround right now is to draw polygons after addentities and it won't break, but it'd be nice that you could draw polygons without depth write before entities

![fte-20230116223823-0](https://user-images.githubusercontent.com/10912941/212764153-60c8113f-722d-45bd-baac-007cb6c18b94.png)

**Comment by fhomolka** [comment]
Interesting note discovered while trying to reproduce this: if the `setproperty` builtin is called after `R_EndPolygon`, the issue does not occur. Property accessed and the value do not matter.

**Comment by fhomolka** [comment]
[Polygon_bbox_issue_minimal.zip](https://github.com/fte-team/fteqw/files/12001570/Polygon_bbox_issue_minimal.zip)

Here is a minimal reproducible project, based on sui-qc. The offender is in src/cl_main.qc
