### ISSUE TITLE
Dimension of the Machine's mge1m1 crashes game client

### ISSUE THREAD

**Issue by Xylemon** [fte-team/fteqw#169]
Shortly after running into enemies in the first mission level, the game will terminate early with this error:

```
    0 1b 34 41 43 48 5f 46 52 49 45 4e 44 4c 59 5f 46 94ACH_FRIENDLY_F
   16 49 52 45  0  -  -  -  -  -  -  -  -  -  -  -  - IRE.XXXXXXXXXXXX
Host_EndGame: CLNQ_ParseServerMessage: Illegible server message (76@12)
```

Tested on latest version.

**Comment by eukara** [comment]
We couldn't replicate this again. Closing.

**Comment by Xylemon** [comment]
Seems the issue is playing in `-netquake` mode will cause the crash, due to the achievement events that the monsters have. It's best anyways to play in QuakeWorld mode for this addon, since there aren't even any demos.

**Comment by eukara** [comment]
`-game mg1` isn't designed to be played with the -netquake compatibility mode, unless @Shpoike wants to add some filter to let it continue anyhow. the netquake compat mode also doesn't expect any particularily high limits so you might run into issues later anyway.
