### ISSUE TITLE
Quake 2 save game causes crashes with latest binary on Debian

### ISSUE THREAD

**Issue by daemonspudguy** [fte-team/fteqw#17]
I have a log file
[crash.log](https://github.com/fte-team/fteqw/files/10252323/crash.log)

**Comment by eukara** [comment]
Fixed in our branch over at https://github.com/VeraVisions/fteqw/commit/e8895637b9a7491c19206d4a7cb5ea9121e04ad2

Will make sure this gets pushed upstream here soon and will close this Issue once that has happened.
Thank you again!

**Comment by daemonspudguy** [comment]
@eukara I would recommend creating a pull request as well.

**Comment by Xylemon** [comment]
https://sourceforge.net/p/fteqw/tickets/125/ has been merged into this issue.

---

@eukara wrote on 2022-03-01:

This is with using the ASLR-friendly Yamagi Quake II game binaries.

Reproduce:
```
maxplayers 1; map base1
save test
disconnect
load test
```

**Comment by Xylemon** [comment]
This should be fixed now.

**Comment by daemonspudguy** [comment]
I won't be able to test for a few days as my monitor and chair both broke last night and I'm waiting for a replacement monitor to be shipped.
