### ISSUE TITLE
[HeXen II] "Always Run" option doesn't work

### ISSUE THREAD

**Issue by Muleke** [fte-team/fteqw#172]
Title. I have to use the console command "cl_run 1" to enable the feature.

I haven't tested this in other Quake engine games, only in HeXen II with FTEQW Revision 6343.

**Comment by Xylemon** [comment]
Using the latest revision (6420) and launching with "-hexen2", the menu's "always run" will function just fine.

Side note:

it seems the menu changes two cvars, `cl_backspeed ` and `cl_forwardspeed` while not changing `cl_run`. Interestingly enough, `cl_run` also works but it's not affected by the menu. Not sure if this should be addressed, but on the bright side, the menu should "just work" now.
