### ISSUE TITLE
SIGSEGV in MasterInfo_ProcessHTTP()

### ISSUE THREAD

**Issue by ewhac** [fte-team/fteqw#174]
The issue is here:

https://github.com/fte-team/fteqw/blob/d76d14294986cabc0dcc626237eb2b8473c8ac0e/engine/client/net_master.c#L2770

If `brokerid` is NULL, this will segfault.  I added a `printf()` to print out the original string `s` if `brokerid` was ever NULL.  I got this:

```
187.20.88.66:26001
```

This is causing my locally-built client to konk out whenever I try to join a game, fetching the server list.  Do I have a stale cache file I need to get rid of?  Or is this an actual issue?

**Comment by eukara** [comment]
Spoike told me that there was a crash with the server browser with the latest commits and told me to put off on building new release binaries. I assume this is probably the reason.
