### ISSUE TITLE
HTTP response body not provided when response code is 202

### ISSUE THREAD

**Issue by hemebond** [fte-team/fteqw#175]
When making an HTTP request from QuakeC using uri_get, the response body is not passed to the callback function when the response code is 202, the way it is for 200.

Updating the HTTP_DL_Work function fixes it:

```diff
diff --git a/engine/http/httpclient.c b/engine/http/httpclient.c
index 528468e3a..f4b0d15ca 100644
--- a/engine/http/httpclient.c
+++ b/engine/http/httpclient.c
@@ -795,7 +795,7 @@ static qboolean HTTP_DL_Work(struct dl_download *dl)
                                return true;
                        }
 
-                       if (stricmp(buffer, "200"))
+                       if (stricmp(buffer, "200") && stricmp(buffer, "202"))
                        {
                                nl = strchr(msg, '\n');
                                if (!nl)
```

Should also provide the response body for 201.

**Comment by eukara** [comment]
Got the OK from @Shpoike to go ahead with this, addressed in https://github.com/fte-team/fteqw/commit/aa8fcb02964e4e2a6b70bbe964dbf9e72ed0f3f0. Thanks!
