### ISSUE TITLE
Sounds repeat until snd_restart

### ISSUE THREAD

**Issue by hemebond** [fte-team/fteqw#181]
Running `fteqw-sdl2` (including built from latest main branch), when I load a new map, or map_restart, all sounds being played will start looping infinitely, e.g., jumping, shooting, menus, etc. I have to `snd_restart` to fix it, and do it every time a map is started.

**Comment by hemebond** [comment]
That resolved the issue. Thank you.

**Comment by Xylemon** [comment]
Closing as this is technically a duplicate of #170

**Comment by hemebond** [comment]
@Xylemon Just a heads-up, this is still a problem. I had to find this issue to get the solution again.
