### ISSUE TITLE
How to rotate maps in classic DM server using FTEQW?

### ISSUE THREAD

**Issue by paulogagliardi** [fte-team/fteqw#184]
Man, the Quake Total Destruction server with mapcycle with fteqw is awesome. Check it out: arenacamper.ddns.net:26000
I got now 110 maps cycling there... and there will be more... =)

Please, can we do the same to a Quake DM server with fteqw without mod? Basically a classic FFA server with mapcycle.

**Comment by paulogagliardi** [comment]
Already solved to DM with this solution: https://github.com/eukara/td2qw/commit/8da82704e887b782e882f847a226153ae5b63048
=)

The server is: arenacamper.ddns.net:26000 [QN/QW classic FFA]

http://arenacamper.125mb.com

**Comment by paulogagliardi** [comment]
WOW! Man, map voting could be awesome using the maps in the qw/maps directory. Typing the map's name like KTX does.

**Comment by paulogagliardi** [comment]
Hey, how did you put [SERVEME] in idtech.space:27500 server using FTEQW?
When I use it in Arena Camper with FTEQW, the server crash. It works OK only in MVDSV server.

**Comment by eukara** [comment]
I didn't do that, I think there's a bot scraping the master server and just inserts itself into whatever game it can.
