### ISSUE TITLE
Issues with Q2PRO's protocol 36 compatibility

### ISSUE THREAD

**Issue by fhomolka** [fte-team/fteqw#189]
Brought up by Phatman in this message on the Level Design discord: https://discord.com/channels/308335417105842177/360596986392739840/1122486107293097994

There seems to be issues with entity rendering when FTE connects to a Q2PRODED server
Screenshots:

![fte-20230624233908-0](https://github.com/fte-team/fteqw/assets/21170980/7bddd38e-0a89-41e7-a835-65d3c2ef092d)
![fte-20230624233847-0](https://github.com/fte-team/fteqw/assets/21170980/fd06d080-2bc7-4523-8ebb-1c41da1722c4)
![fte-20230624231425-0](https://github.com/fte-team/fteqw/assets/21170980/6915883b-9290-431d-b74a-6fcb6f4bd6f5)

**Comment by ThePhatman** [comment]
The Q2PRO server reported that the client was connected using protocol 36.

Issues we noticed were:
1. Entities appeared transparent
2. We could see entities even if they were behind walls
3. Entities would appear off to our left when they were actually on our right and vice-versa
4. The clientNum feature was not working properly (for in-eyes spectator view of another client); the target entity's model was still showing and should not be when using the clientNum feature

**Comment by eukara** [comment]
Been trying to reproduce this with a dedicated server running q2proded-git [2d4906b](https://github.com/skullernet/q2pro/commit/2d4906be98764de3502be4bababa78f946bd2cf5) I'm hosting at idtech.space:27910 and I'm unable to get the protocols to switch to 36. I'll try it in a listen environment next.

**Comment by ThePhatman** [comment]
Alright, so the client FTE version I'm using is 2.57 FTE SVN 6202.
We are using the same Q2PRODED versions.
After connecting the client to the server and typing status on the latter, I see the following (IP address redacted):

num score ping name            lastmsg address                rate pr fps
--- ----- ---- --------------- ------- --------------------- ----- -- ---
  0     0    2 Phatman              12 ADDRESS:PORT         15000 36 128

It notes the client as using protocol 36 under the "pr" header.
It notes 35 for R1Q2 and 34 for Yamagi clients, for instance.
Of course I'm looking at this from the server's interpretation regarding what protocol version was negotiated...

**Comment by eukara** [comment]
https://github.com/fte-team/fteqw/pull/200 Should hopefully address this issue @Shpoike
