### ISSUE TITLE
Remove Visual Studio project files

### ISSUE THREAD

**Issue by Xylemon** [fte-team/fteqw#193]
As @Shpoike mentioned in #156 these are deprecated in favor of CMake, so unless there is any objections, this old unmaintained cruft should probably be tossed.

**Comment by Shpoike** [comment]
there's a number of associated outdated library files that should be purged at the same time, which would be nice for shallow clones at least.

**Comment by eukara** [comment]
> there's a number of associated outdated library files that should be purged at the same time, which would be nice for shallow clones at least.

engine/libs/{dxsdk7,dxsdk9,vc6-libs} would probably the lot

**Comment by Shpoike** [comment]
probably the entire engine/libs/ dir. the makelibs thing will generally download them to compile per-platform stuff, while the cmake project will simply disable any missing third-party dependencies - msvc will probably have libc/linker issues with our outdated libs anyway while mingw+linux have package managers that should easily provide their own.
If third party stuff is actually needed in the repo then it should probably be one of these git submodule things anyway.

**Comment by eukara** [comment]
I will look over the PR later today once I'm clear. Thank you @Xylemon for putting a PR draft together.
