### ISSUE TITLE
fteqcc autoproto causes compilation to fail on accessor

### ISSUE THREAD

**Issue by hemebond** [fte-team/fteqw#202]
When enabling autoproto in the progs.src file:

```
#pragma autoproto
```

compilation fails on these lines:

```
accessor jsonnode : json_t;
...
accessor jsonnode : json_t
{
```

with this error:

```
compiling qc/sv_defs.qc
qc/sv_defs.qc:1365: error: Accessor jsonnode basic type mismatch
qc/sv_defs.qc:2058: error: Accessor jsonnode basic type mismatch
```

**Comment by fhomolka** [comment]
This was already fixed, please update your [FTEQCC](https://www.fteqcc.org)
Autoproto does have other issues, though. So I'll try to track down those

**Comment by Xylemon** [comment]
Thanks for testing, please feel free to open an issue related to the typedef failure.

**Comment by hemebond** [comment]
> feel free to open an issue related to the typedef failure.

I just tested again and it doesn't seem to have a problem with typedef.
