### ISSUE TITLE
.dimension_hit/solid are broken

### ISSUE THREAD

**Issue by RennyC4** [fte-team/fteqw#205]
It appears as though dimension_hit ignores dimension_solid.

.dimension_solid = 0x02 gets hit by .dimension_hit = 0x01, zeroing dimension_hit will not hit anything, any other values does
regardless of what dimension_solid is set to.

**Comment by eukara** [comment]
Can you provide a test case?

**Comment by RennyC4** [comment]
First grab RenRacer (includes source) https://github.com/RennyC4/RenRacer

Check out main.qc where player_dimension_hit/player_dimension_solid are stored, basically deathmatch turns on FLAG_1/2 for hit and solid respectively and deathmatch being off sets it to 0. 0 works, FLAG_1/2 or 0x01/0x02 do not.

FLAG_# Table is as:
// Define bitmask constants
#define FLAG_1 (1 << 0)  // 00000001
#define FLAG_2 (1 << 1)  // 00000010
#define FLAG_3 (1 << 2)  // 00000100
#define FLAG_4 (1 << 3)  // 00001000
#define FLAG_5 (1 << 4)  // 00010000
#define FLAG_6 (1 << 5)  // 00100000
#define FLAG_7 (1 << 6)  // 01000000
#define FLAG_8 (1 << 7)  // 10000000

Flag table is located in defs.qc as an easily referenced table.

Players shouldn't be able to drive into each other at all but should be blocked by bmodels, so once this is fixed I can use FLAG_1/2 properly for both deathmatch and deathmatch off and remove setting solid/hit to 0.

**Comment by RennyC4** [comment]
Forgot to mention, vehicles call PushPlayers(); (client.qc) which is a simple radius find for fake collisions I wrote (since func_vehicles particle physics have a math bug that can cause issues; a great reason why I also need dimension stuff working). Just so you don't get confused as to why they still 'hit' each other :)

**Comment by RennyC4** [comment]
Good news. False positive of a bug report, I forgot to make the func_vehicles hitmodel stuff adhere to dimension_hit/solid (it's a complicated entity with a lot of parts); thanks to spike pointing it out everything works as it should!
