### ISSUE TITLE
Map votation using FTEQW - is it possible?

### ISSUE THREAD

**Issue by paulogagliardi** [fte-team/fteqw#209]
I'm trying to implementating MAP VOTATION in a Quake 1 FFA server (using fteqw, course)

The idea is to do like KTX mod: typing the name of the map in the console and starts a votation for that map. (or typing a command followed by map name - anyway)

I read something about "void changelevel(string mapname)" in quakeC manual, but I don´t know how to use it in the source code. In fact I don´t know if i am in the right direction. 

Please... can you help me about this?

**Comment by eukara** [comment]
Join my QW game server at `idtech.space` and use the following message via chat:

`callvote map dm4`

and people can vote `yes` or `no` in chat. if you're the only one on the server, it'll pass the vote right away.
you can also `callvote kick` to get rid of pesky players. all done with standard QuakeC.

is that something you're looking for? if yes, I can clean up and share the source code that's running on the server.

**Comment by paulogagliardi** [comment]
Mr. eukara:

Amazing server! This votation to maps is exactly what I´m looking.
Please, can you share the source code? I will put it on 2 FTEQW servers... and they will be complete. =)

**Comment by eukara** [comment]
Here you go: https://code.idtech.space/eukara/quake-qw-qc

[Check the latest commit](https://code.idtech.space/eukara/quake-qw-qc/commit/d499fc138da158917ce0c4772184e40f990ce26d) which should show everything that's new/needed.

Glad to be of help!

**Comment by paulogagliardi** [comment]
Man, it worked fine to the FFA server! Now it´s 100% workly. =)

But, when I try to do the same for server with TD2 mod, it give the error:

compiling voting.qc
in function ChatMessage_Parse (line 61),
voting.qc:79: error: Cannot cast from float to string

************ ERROR ************
compilation errors
Error in voting.qc on line 79

I tried to do some changes and consult the QuakeC manual. But nothing worked.
Already seen this error?

I updated the files of mod here: https://github.com/paulogagliardi/td2qw

**Comment by eukara** [comment]
It seems you have to modify the line 79 inside voting.qc to use `qw_bprint` instead of `bprint`.

**Comment by paulogagliardi** [comment]
It WORKED!

Thanks Mr eukara!

Yes, Total Destruction (TD) is a brazilian mod, made for NQ. And he was ported to QW some years later.

Thank you for you support. My servers are complete now! xD

arenacamper.ddns.net:26000 [DM classic]
arenacamper.ddns.net:27500 [TD2 server]

**Comment by Xylemon** [comment]
Glad to hear, going to close this issue if that's alright. Feel free to open another or join the Matrix/IRC if you have any more questions.
