### ISSUE TITLE
¿Does anyone know how to install FTEQCC in Manjaro?

### ISSUE THREAD

**Issue by perondeidad** [fte-team/fteqw#214]

**Comment by eukara** [comment]
We don't provide official packages for Manjaro. If you'd like to build it from source, you can find instructions here:
https://www.fteqw.org/compiling.html

Otherwise, the binaries provided on https://www.fteqw.org/ should be portable enough to run as-is on Manjaro.

**Comment by perondeidad** [comment]
I think I have solved it? , I converted a .DEB package to .pkg.tar.gz and installed it. So far I have had no problems. Os ire actualizado en caso que tenga problemas

**Comment by Xylemon** [comment]
Glad to hear it worked for you, but as stated above this is not a problem with FTE. Closing.
