### ISSUE TITLE
"Game Mismatch: This is a FTE-Quake Server"

### ISSUE THREAD

**Issue by ZecChelovek** [fte-team/fteqw#215]
https://i.imgur.com/WNAy4Uu.png
Trying to host a dedicated FTE server from a remote virtual machine. This pops up when trying to connect from my own machine. Not only that, 
https://i.imgur.com/wXuw67L.png

As the text suggests, FTE cannot see ammo boxes. I assume it's because they have to be outside of the pak right?

**Comment by eukara** [comment]
What does the cvar `com_protocolname` report on your client?

And no, it should totally see everything within .pak files.

**Comment by ZecChelovek** [comment]
Hoho, thanks! I had forgotten I had set up some files to play Dimension of the Machine on Ironwail so "com_protocolname" was "FTE-Quakererelease". With the files removed, now it's "FTE-Quake DarkPlaces-Quake". A stranger issue now: 
https://i.imgur.com/50RqVdA.png
https://i.imgur.com/9lPYCH3.png
This happens with both Zerstorer mod, and id1. Download of maps/start denied by server, and it is in a "copyrighted pak". Very strange because both the remote machine and mine have Zer and id1.

**Comment by Shpoike** [comment]
the lack of the .bsp extension in all those prints is a bug in your server's build (the maplist command iirc, which corrupts internal pak state) that's already fixed, its resulting in the client being told a truncated filename which it naturally doesn't possess with the server thinking it does and that it can be found in a numbered pak (which you're not permitted to download from).

the Game Mismatch stuff is technically correct when the rerelease contains incompatible maps (different inline models), but kinda obnoxious for the majority of maps that have only checksum errors.
you can work around it by putting the other protocol's name onto the end of your com_protocolname cvar (space-separated list of accepted protocols, with the server registering to masters using only the first name).
I don't know what the ideal default behaviour should be here, the mechanism is meant to help isolate standalone games more easily but I suspect its getting in the way of ordinary usage.

**Comment by ZecChelovek** [comment]
> the lack of the .bsp extension in all those prints is a bug in your server's build (the maplist command iirc, which corrupts internal pak state) that's already fixed, its resulting in the client being told a truncated filename which it naturally doesn't possess with the server thinking it does and that it can be found in a numbered pak (which you're not permitted to download from).

Already fixed as in no longer an issue? Or fixed as in unchangeable? Is there a remedy for my issue? Appreciate the man himself replying.

**Comment by Xylemon** [comment]
Please comment if there is still an issue.
