### ISSUE TITLE
Quake 1 OGG music does not loop in `3adec5d`

### ISSUE THREAD

**Issue by nashmuhandes** [fte-team/fteqw#216]
Build `3adec5d` downloaded from FTEQW.org - seems that OGG music no longer loops.

**Comment by Theuaredead** [comment]
Does the song repeat but have a second or 2 of nothing before it plays again or is it not looping/repeating at all?

**Comment by nashmuhandes** [comment]
> Does the song repeat but have a second or 2 of nothing before it plays again or is it not looping/repeating at all?

Does not repeat at all. Complete silence even after standing there for more than a minute. :)

**Comment by Xylemon** [comment]
It's strange because I can't reproduce with latest binaries on Linux or Windows 7, but we'll keep investigating.
