### ISSUE TITLE
How do I compile it for GLES?

### ISSUE THREAD

**Issue by raduprv** [fte-team/fteqw#237]
I'm trying to compile it for an Orange Pi Zero 2W, and it complains about not finding the GL headers. How would one compile it for GLES instead?

**Comment by eukara** [comment]
All one theoretically needs is the GL devel package.
If the GL context is GLES then FTE will use that.

There's a #GLESONLY define that's being used for the Web/Android port, in case you would have to force it (`CFLAGS="-DGLESONLY"` passed in front of `make` )

**Comment by raduprv** [comment]
Great, it worked, thank you very much! I still had to install  lot of other library devel packages to get it to work, but in in the end I managed to compile the binary :) I also had to add another .1 at the end of the zlib version in the makefile, so it reads 1.3.1 (it couldn't find the tar.gz for the 1.3 version)
