### ISSUE TITLE
I want to know the remaining times of air and powerups like quad damage, pentagram of protection, ring of shadows and bio suit

### ISSUE THREAD

**Issue by FeatureRequestor** [fte-team/fteqw#240]
When underwater the player has about 12 seconds until he is drown but the information when this will happen is hidden.

This is also true for all the powerups like quad damage (that multiplies inflict damage by 4), pentagram of protection (that makes player invulnerable), ring of shadows (that makes player invisible) and bio suit (that allows player to breathe underwater).

They all last about 30 seconds but the information about when each is expired is hidden too.

I would like to always know when something happens by drawing text, number or bar showing the remaining time until it happens.

**Comment by Xylemon** [comment]
Won't add for reasons stated in #239.
