### ISSUE TITLE
I can't compile fteqw for windows

### ISSUE THREAD

**Issue by ghost** [fte-team/fteqw#241]
I tried in the engine directory:

make makelibs FTE_TARGET=win64
make gl-rel FTE_TARGET=win64

But I see these errors:

/mnt/d/Backup/Source/fteqw-master/engine/gl/gl_font.c:60:10: error: #include expects "FILENAME" or <FILENAME>
   60 | #include FT_FREETYPE_H
      |          ^~~~~~~~~~~~~
make[4]: [Makefile:1840: /mnt/d/Backup/Source/fteqw-master/engine/release/m_linux/gl_font.o] Error 1 (ignored)
/mnt/d/Backup/Source/fteqw-master/engine/gl/gl_font.c:59:10: fatal error: ft2build.h: No such file or directory
   59 | #include <ft2build.h>

I have already installed FreeType with `sudo apt-get install libfreetype6-dev` but this doesn't help at all

I even tried:

make clean
make all

but this doesn't help either

Additionally make makelibs FTE_TARGET=win64 also reports these errors:

HTTP request sent, awaiting response... 404 Not Found
2024-03-03 03:44:51 ERROR 404: Not Found.

make: *** [Makefile:2303: libs-x86_64-linux-gnu/libz.a] Error 8

**Comment by Xylemon** [comment]
Closing due to your previous behavior on our issue tracker.
