### ISSUE TITLE
Add quad to Aerowalk

### ISSUE THREAD

**Issue by paulogagliardi** [fte-team/fteqw#253]
Please, is there a way to add quad to Aerowalk map using FTE-QW?

**Comment by Xylemon** [comment]
Yes, you can dump the plaintext entity lump from a compiled map and edit it. This can be done with the console command `sv_saveentfile` and the entity lump will be saved alongside the map in a ".ent" text file, for example:

	maps/aerowalk.bsp
	maps/aerowalk.ent

Edit the ".ent" file in your text editor of choice to add your custom entities, reload the map and have fun.
