### ISSUE TITLE
FTEQW feels choppy at 4k and my OSD flickers

### ISSUE THREAD

**Issue by CorpusBava** [fte-team/fteqw#266]
Maybe I've played too much with Ironwail and vkQuake but I recently tested FTEQW (whivh i plan to play Nehahra with) and it's feeling choppy especially when I turn.  I'm using an RTX 3070 and the the FPS counter says a constant 120 FPS.  I have vsync set to Strict and tested other vsync modes and it's the same.  Contrast that with IR and vkQuake where it's butter smooth.  Also, my OSD set to show framrate and gpu/cpu temps flickers, fullscreen or borderl;ss window Is there a tweak I can do to get it smooth?  My display is g-sync/VRR enabled.

**Comment by Xylemon** [comment]
This sounds like it is related to issue #179 where FTEQW is struggling with a change done in the RTX series of nVidia GPUs.

**Comment by CorpusBava** [comment]
> This sounds like it is related to issue #179 where FTEQW is struggling with a change done in the RTX series of nVidia GPUs.

I guess there's nothing that can be done then if it's an RTX issue, outside of buying a new card.  I'm using Mark V now to play Nehahra and, amazingly, it's almost as smooth as Ironwail and vkQuake once I enabled vsync at 120 hz/fps.  Haven't run into any physics bugs yet.  I hope to try FTEQW again someday (I like it's 5.1 audio support) when things are eventually fixed for RTX cards.

**Comment by Xylemon** [comment]
Merging into issue #179.
