### ISSUE TITLE
zlib version 1.2.12, specified in Makefile, no longer available.

### ISSUE THREAD

**Issue by fhomolka** [fte-team/fteqw#4]
zlib 1.2.12 is no longer available. 
The new version is 1.2.13.

Unfortunately, they're not hosting the older version anymore, so bumping up the version specified in the Makefile is required for `makelibs`

After that all works well :)

**Comment by eukara** [comment]
Thanks, will be addressed soon! We're currently in the process of migrating from SVN to git so changes can occur more often on this repo - still gotta migrate a few scripts over.

**Comment by Xylemon** [comment]
This has been fixed now.
